switcher.context=com.github.switcherapi.PlaygroundFeatures
switcher.url=https://api.switcherapi.com
switcher.apikey=${API_KEY:}
switcher.component=switcher-playground
switcher.environment=${ENVIRONMENT:default}
switcher.domain=Playground

#optional
switcher.local=${LOCAL:false}
switcher.snapshot.location=./src/main/resources/snapshots
switcher.snapshot.auto=${SNAPSHOT_AUTO:false}
switcher.auth.autorefresh=true
switcher.silent=
switcher.retry=