switcher.context=com.github.switcherapi.PlaygroundFeatures
switcher.url=https://api.switcherapi.com
switcher.apikey=${SWITCHER_API_KEY:}
switcher.component=switcher-playground
switcher.environment=default
switcher.domain=Playground

#optional
switcher.local=${LOCAL:false}
switcher.snapshot.location=${SNAPSHOT_LOCATION:}
switcher.snapshot.auto=${SNAPSHOT_AUTO:false}
switcher.silent=${SWITCHER_SILENT:}