.PHONY: install-test install play

install-test:
	pip install -r requirements.txt --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/

install:
	pip install -r requirements.txt

play:
	python src/main.py
