server:
   port: 8070

logging:
   level:
      com.github.switcherapi.client: DEBUG
      org.springframework.web: INFO

switcher:
   contextLocation: com.github.switcherapi.config.Features
   url: https://api.switcherapi.com
   apikey: ${SWITCHER_APIKEY}
   component: switcher-playground
   domain: Playground

   # optional
   local: ${LOCAL:true}
   check: true
   snapshot:
      location: ./src/main/resources/snapshots
      auto: ${SNAPSHOT_AUTO:true}
      watcher: true
      updateInterval: 5s
   silent: 1m